version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building application..."
      - npm run build  # This will execute the script defined in your package.json (or a placeholder if no script exists)

  post_build:
    commands:
      - echo "Build completed!"  # Optional step to indicate build completion


